version: '3'
services:
  localstack:
    image: localstack/localstack
    container_name: lloyd_localstack
    ports:
      - "4567-4583:4567-4583"
      - "8181:8181"
    environment:
      - SERVICES=s3,lambda,sqs,sns
      - DEFAULT_REGION=eu-west-1
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - PORT_WEB_UI=8181
      - LAMBDA_EXECUTOR=docker
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
